# Generated by Django 3.1.3 on 2020-12-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
