# Generated by Django 3.1.3 on 2020-12-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201219_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
